POST http://127.0.0.1:5000/tasks
Content-Type: application/json

{
    "name": "運動十分鐘",
    "priority": 3,
    "importance": 3
}

###

GET http://127.0.0.1:5000/tasks


###
PUT http://127.0.0.1:5000/tasks/3
Content-Type: application/json

{

}

###

DELETE http://127.0.0.1:5000/tasks/3
Content-Type: application/json

{

}

###